"""add admin_videos table

Revision ID: 5da6e6d999e9
Revises: b3f094352350
Create Date: 2026-05-19 22:19:21.566489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da6e6d999e9'
down_revision: Union[str, None] = 'b3f094352350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('plataformas', sa.JSON(), nullable=False),
    sa.Column('publish_status', sa.String(), nullable=True),
    sa.Column('publish_error', sa.String(), nullable=True),
    sa.Column('tiktok_video_id', sa.String(), nullable=True),
    sa.Column('tiktok_short_link', sa.String(), nullable=True),
    sa.Column('youtube_video_id', sa.String(), nullable=True),
    sa.Column('youtube_short_link', sa.String(), nullable=True),
    sa.Column('tiktok_views', sa.Integer(), nullable=True),
    sa.Column('youtube_views', sa.Integer(), nullable=True),
    sa.Column('clicks_total', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_videos')
    # ### end Alembic commands ###
