"""initial_schema

Revision ID: bef783622397
Revises: 
Create Date: 2026-05-17 23:01:27.530775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef783622397'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alertas_telegram_id', table_name='alertas')
    op.drop_column('alertas', 'telegram_id')
    op.create_index(op.f('ix_conversion_events_external_order_id'), 'conversion_events', ['external_order_id'], unique=False)
    op.drop_column('conversion_events', 'last_error')
    op.drop_column('conversion_events', 'retry_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversion_events', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('conversion_events', sa.Column('last_error', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_conversion_events_external_order_id'), table_name='conversion_events')
    op.add_column('alertas', sa.Column('telegram_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_alertas_telegram_id', 'alertas', ['telegram_id'], unique=False)
    # ### end Alembic commands ###
