/**
 * brands.ts — Configuração das páginas de marca (hubs por fabricante).
 *
 * Cada marca mapeia para /marca/[slug] e contém queries populares
 * para buscar produtos daquela marca.
 */

export interface BrandConfig {
  slug: string
  name: string
  description: string
  icon: string
  queries: string[]
  related: string[]
}

export const BRANDS: BrandConfig[] = [
  {
    slug: "apple",
    name: "Apple",
    description: "iPhones, MacBooks, AirPods, Apple Watch e acessórios Apple com os menores preços do Brasil.",
    icon: "",
    queries: [
      "iphone-16-pro-max", "iphone-16-pro", "iphone-16", "iphone-15-pro-max",
      "iphone-15-pro", "iphone-15", "iphone-15-plus", "iphone-14-pro-max",
      "iphone-14", "iphone-13", "iphone-12", "iphone-se",
      "macbook-air-m3", "macbook-air-m2", "macbook-pro-14", "macbook-pro-16",
      "ipad-10", "ipad-air", "ipad-pro", "ipad-mini",
      "airpods-pro-2", "airpods-4", "airpods-max",
      "apple-watch-series-10", "apple-watch-se", "apple-watch-ultra-2",
      "magic-keyboard", "apple-pencil", "magsafe-carregador",
    ],
    related: ["samsung", "xiaomi", "sony"],
  },
  {
    slug: "samsung",
    name: "Samsung",
    description: "Samsung Galaxy, Smart TVs, Galaxy Buds, tablets e eletrodomésticos Samsung com melhores preços.",
    icon: "📱",
    queries: [
      "samsung-galaxy-s25-ultra", "samsung-galaxy-s25", "samsung-galaxy-s24",
      "samsung-galaxy-a55", "samsung-galaxy-a35", "samsung-galaxy-m55",
      "samsung-galaxy-z-fold-6", "samsung-galaxy-z-flip-6",
      "smart-tv-samsung-50", "smart-tv-samsung-55", "smart-tv-samsung-65",
      "smart-tv-samsung-43", "smart-tv-samsung-75", "tv-qled-samsung",
      "galaxy-buds-3", "galaxy-buds-3-pro", "galaxy-buds-2-pro",
      "tablet-samsung-s9", "tablet-samsung-a9", "tablet-samsung-s10",
      "samsung-galaxy-watch-7", "samsung-galaxy-watch-ultra",
      "geladeira-samsung", "lava-louca-samsung", "ar-condicionado-samsung",
    ],
    related: ["apple", "lg", "xiaomi"],
  },
  {
    slug: "lg",
    name: "LG",
    description: "Smart TVs LG OLED, geladeiras, lavadoras, ar-condicionado e eletrodomésticos LG em oferta.",
    icon: "📺",
    queries: [
      "smart-tv-lg-50", "smart-tv-lg-55", "smart-tv-lg-65", "smart-tv-lg-43",
      "tv-lg-oled-55", "tv-lg-oled-65", "tv-lg-nano-55", "tv-lg-nano-65",
      "geladeira-lg", "lava-e-seca-lg", "maquina-de-lavar-lg",
      "ar-condicionado-lg", "microondas-lg", "lava-louca-lg",
      "soundbar-lg", "home-theater-lg", "caixa-de-som-lg",
      "monitor-lg-ultrawide", "monitor-lg-27", "monitor-lg-32",
    ],
    related: ["samsung", "philips", "sony"],
  },
  {
    slug: "sony",
    name: "Sony",
    description: "PlayStation 5, headphones Sony, soundbars, câmeras Sony e eletrônicos com menores preços.",
    icon: "🎮",
    queries: [
      "playstation-5", "ps5-slim", "ps5-pro", "controle-ps5",
      "jogo-ps5", "ps5-dualsense", "ps5-pulse-3d",
      "headphone-sony-wh-1000xm5", "headphone-sony-wh-1000xm4",
      "fone-sony-wh-520", "caixa-de-som-sony", "soundbar-sony",
      "camera-sony-alpha", "camera-sony-zv1", "lente-sony",
      "tv-sony-bravia", "tv-sony-55", "tv-sony-65",
    ],
    related: ["microsoft", "samsung", "bose"],
  },
  {
    slug: "microsoft",
    name: "Microsoft",
    description: "Xbox Series X/S, jogos Xbox, acessórios, Surface e Windows com melhores ofertas.",
    icon: "🎮",
    queries: [
      "xbox-series-x", "xbox-series-s", "controle-xbox", "xbox-elite",
      "jogo-xbox", "xbox-game-pass", "gift-card-xbox",
      "surface-pro-9", "surface-laptop-5", "surface-go",
      "windows-11", "office-365", "xbox-headset",
      "xbox-storage-1tb", "xbox-bateria", "xbox-volante",
    ],
    related: ["sony", "nintendo", "logitech"],
  },
  {
    slug: "nintendo",
    name: "Nintendo",
    description: "Nintendo Switch, jogos Switch, acessórios e amiibos com menores preços.",
    icon: "🍄",
    queries: [
      "nintendo-switch", "nintendo-switch-oled", "nintendo-switch-lite",
      "jogo-nintendo-switch", "controle-nintendo-switch", "nintendo-pro-controller",
      "mario-kart-deluxe", "zelda-tears-of-the-kingdom", "super-mario-bros-wonder",
      "nintendo-amiibo", "nintendo-switch-case", "nintendo-memory-card",
    ],
    related: ["sony", "microsoft", "logitech"],
  },
  {
    slug: "xiaomi",
    name: "Xiaomi",
    description: "Redmi, Poco, Xiaomi Band, scooters e acessórios Xiaomi com os menores preços.",
    icon: "📱",
    queries: [
      "redmi-note-13-pro", "redmi-note-13", "redmi-note-12",
      "poco-x6-pro", "poco-x6", "poco-f6",
      "xiaomi-14", "xiaomi-13", "xiaomi-redmi-13c",
      "xiaomi-band-8", "xiaomi-band-7", "xiaomi-smart-band",
      "xiaomi-scooter", "xiaomi-air-fryer", "xiaomi-robot-vacuum",
      "redmi-buds", "xiaomi-buds-4", "xiaomi-power-bank",
    ],
    related: ["apple", "samsung", "motorola"],
  },
  {
    slug: "motorola",
    name: "Motorola",
    description: "Moto Edge, Moto G, Moto One e acessórios Motorola com melhores preços.",
    icon: "📱",
    queries: [
      "motorola-edge-50", "motorola-edge-40", "motorola-edge-30",
      "moto-g84", "moto-g54", "moto-g34", "moto-g14",
      "motorola-one-edge", "motorola-defy",
      "capa-motorola", "carregador-motorola",
    ],
    related: ["xiaomi", "samsung", "apple"],
  },
  {
    slug: "jbl",
    name: "JBL",
    description: "Caixas de som JBL, fones Bluetooth, soundbars e speakers portáteis em oferta.",
    icon: "🔊",
    queries: [
      "jbl-flip-6", "jbl-flip-5", "jbl-charge-5", "jbl-charge-4",
      "jbl-go-4", "jbl-go-3", "jbl-clip-4", "jbl-clip-3",
      "jbl-tune-520bt", "jbl-tune-510bt", "jbl-tune-770bt",
      "jbl-live-770nc", "jbl-endurance-run",
      "soundbar-jbl", "jbl-partybox", "jbl-extreme-3",
    ],
    related: ["sony", "bose", "lg"],
  },
  {
    slug: "bose",
    name: "Bose",
    description: "Headphones Bose QuietComfort, soundbars e fones sem fio com menores preços.",
    icon: "🎧",
    queries: [
      "bose-quietcomfort-ultra", "bose-quietcomfort-45", "bose-quietcomfort-35",
      "bose-noise-cancelling", "bose-soundlink-flex",
      "bose-soundlink-max", "bose-soundlink-mini",
      "soundbar-bose", "bose-700", "bose-a30",
    ],
    related: ["sony", "jbl", "apple"],
  },
  {
    slug: "philips",
    name: "Philips",
    description: "Philips Walita, barbeadores, secadores, TVs e eletrodomésticos Philips em oferta.",
    icon: "💡",
    queries: [
      "barbeador-philips", "barbeador-philips-oneblade",
      "tricera-philips", "secador-philips", "prancha-philips",
      "philips-walita-liquidificador", "philips-walita-cafeteira",
      "philips-airfryer", "philips-lampada-led",
      "tv-philips-50", "tv-philips-43", "soundbar-philips",
      "escova-dente-philips", "philips-lumea",
    ],
    related: ["mondial", "electrolux", "lg"],
  },
  {
    slug: "mondial",
    name: "Mondial",
    description: "Airfryer Mondial, liquidificadores, sanduicheiras e eletrodomésticos com menores preços.",
    icon: "🍳",
    queries: [
      "airfryer-mondial", "airfryer-mondial-5l", "airfryer-mondial-4l",
      "liquidificador-mondial", "sanduicheira-mondial",
      "cafeteira-mondial", "panela-eletrica-mondial",
      "ventilador-mondial", "circulador-mondial",
      "ferro-mondial", "batedeira-mondial", "mondial-c200",
    ],
    related: ["philips", "electrolux", "cadence"],
  },
  {
    slug: "electrolux",
    name: "Electrolux",
    description: "Geladeira, lavadora, ar-condicionado, lava-louça e eletros Electrolux em oferta.",
    icon: "🏠",
    queries: [
      "geladeira-electrolux", "geladeira-electrolux-frost-free",
      "maquina-de-lavar-electrolux", "lava-e-seca-electrolux",
      "ar-condicionado-electrolux", "lava-louca-electrolux",
      "microondas-electrolux", "fogao-electrolux",
      "aspirador-electrolux", "cafeteira-electrolux",
      "purificador-electrolux", "bebedouro-electrolux",
    ],
    related: ["brastemp", "consul", "lg"],
  },
  {
    slug: "brastemp",
    name: "Brastemp",
    description: "Geladeira Brastemp, lavadora, lava-louça e eletrodomésticos Brastemp com melhores preços.",
    icon: "🏠",
    queries: [
      "geladeira-brastemp", "geladeira-brastemp-frost-free",
      "maquina-de-lavar-brastemp", "lava-e-seca-brastemp",
      "lava-louca-brastemp", "microondas-brastemp",
      "fogao-brastemp", "cooktop-brastemp",
      "aspirador-brastemp", "bebedouro-brastemp",
    ],
    related: ["consul", "electrolux", "lg"],
  },
  {
    slug: "consul",
    name: "Consul",
    description: "Geladeira Consul, fogão, lavadora e eletrodomésticos Consul em oferta.",
    icon: "🏠",
    queries: [
      "geladeira-consul", "geladeira-consul-frost-free",
      "maquina-de-lavar-consul", "lava-e-seca-consul",
      "lava-louca-consul", "microondas-consul",
      "fogao-consul", "cooktop-consul",
      "bebedouro-consul", "aspirador-consul",
    ],
    related: ["brastemp", "electrolux", "mondial"],
  },
  {
    slug: "dell",
    name: "Dell",
    description: "Notebooks Dell, desktops, monitores e acessórios Dell com menores preços.",
    icon: "💻",
    queries: [
      "notebook-dell-inspiron", "notebook-dell-g15", "notebook-dell-xps",
      "notebook-dell-vostro", "notebook-dell-latitude",
      "monitor-dell-27", "monitor-dell-24", "monitor-dell-ultrasharp",
      "dell-keyboard", "dell-mouse", "dell-dock",
      "notebook-dell-i5", "notebook-dell-ryzen",
    ],
    related: ["lenovo", "acer", "hp"],
  },
  {
    slug: "lenovo",
    name: "Lenovo",
    description: "Notebooks Lenovo IdeaPad, ThinkPad, Legion e acessórios com melhores preços.",
    icon: "💻",
    queries: [
      "notebook-lenovo-ideapad", "notebook-lenovo-thinkpad",
      "notebook-lenovo-legion", "notebook-lenovo-3i",
      "notebook-lenovo-5i", "notebook-lenovo-ryzen",
      "monitor-lenovo", "lenovo-keyboard", "lenovo-mouse",
    ],
    related: ["dell", "acer", "asus"],
  },
  {
    slug: "acer",
    name: "Acer",
    description: "Notebooks Acer Aspire, Nitro, Predator e monitores Acer com menores preços.",
    icon: "💻",
    queries: [
      "notebook-acer-aspire", "notebook-acer-nitro",
      "notebook-acer-predator", "notebook-acer-swift",
      "monitor-acer-27", "monitor-acer-24", "monitor-acer-kg",
    ],
    related: ["dell", "lenovo", "asus"],
  },
  {
    slug: "asus",
    name: "ASUS",
    description: "Notebooks ASUS, placas-mãe, placas de vídeo, monitores ROG e acessórios.",
    icon: "💻",
    queries: [
      "notebook-asus-vivobook", "notebook-asus-rog",
      "notebook-asus-tuf", "notebook-asus-zenbook",
      "placa-mae-asus", "monitor-asus-rog", "monitor-asus-tuf",
      "router-asus", "asus-rt-ax",
    ],
    related: ["acer", "dell", "msi"],
  },
  {
    slug: "logitech",
    name: "Logitech",
    description: "Mouses, teclados, webcams, headsets e periféricos Logitech com menores preços.",
    icon: "🖱️",
    queries: [
      "mouse-logitech-mx-master", "mouse-logitech-g502", "mouse-logitech-g304",
      "teclado-logitech-mx-keys", "teclado-logitech-g915", "teclado-logitech-k380",
      "webcam-logitech-c920", "webcam-logitech-brio",
      "headset-logitech-g733", "headset-logitech-g432",
      "logitech-mx-mini", "logitech-powerplay",
    ],
    related: ["razer", "corsair", "microsoft"],
  },
  {
    slug: "razer",
    name: "Razer",
    description: "Mouses, teclados, headsets e periféricos gamer Razer com menores preços.",
    icon: "🐍",
    queries: [
      "mouse-razer-deathadder", "mouse-razer-viper", "mouse-razer-basilisk",
      "teclado-razer-blackwidow", "teclado-razer-huntsman",
      "headset-razer-kraken", "headset-razer-blackshark",
      "razer-blade-14", "razer-blade-15", "razer-iskur",
    ],
    related: ["logitech", "corsair", "asus"],
  },
  {
    slug: "nike",
    name: "Nike",
    description: "Tênis Nike, roupas esportivas, mochilas e acessórios Nike com menores preços.",
    icon: "👟",
    queries: [
      "tenis-nike-air-max", "tenis-nike-air-force", "tenis-nike-revolution",
      "tenis-nike-corrida", "tenis-nike-pegasus", "tenis-nike-jordan",
      "mochila-nike", "camiseta-nike", "calcao-nike",
      "tenis-nike-masculino", "tenis-nike-feminino",
      "nike-sb", "nike-blazer", "nike-dunk",
    ],
    related: ["adidas", "olympikus", "puma"],
  },
  {
    slug: "adidas",
    name: "Adidas",
    description: "Tênis Adidas, roupas esportivas, mochilas e acessórios Adidas em oferta.",
    icon: "👟",
    queries: [
      "tenis-adidas-corrida", "tenis-adidas-breaknet", "tenis-adidas-grand-court",
      "tenis-adidas-supernova", "tenis-adidas-ultraboost",
      "mochila-adidas", "camiseta-adidas", "calcao-adidas",
      "tenis-adidas-masculino", "tenis-adidas-feminino",
      "adidas-samba", "adidas-forum", "adidas-campus",
    ],
    related: ["nike", "olympikus", "puma"],
  },
  {
    slug: "olympikus",
    name: "Olympikus",
    description: "Tênis Olympikus, roupas esportivas e calçados com menores preços do Brasil.",
    icon: "👟",
    queries: [
      "tenis-olympikus-corrida", "tenis-olympikus-andando",
      "tenis-olympikus-feminino", "tenis-olympikus-masculino",
      "tenis-olympikus-infantil", "olympikus-volei",
      "camiseta-olympikus", "calcao-olympikus",
      "tenis-olympikus-dohms", "tenis-olympikus-flow",
    ],
    related: ["nike", "adidas", "mizuno"],
  },
  {
    slug: "makita",
    name: "Makita",
    description: "Furadeiras, parafusadeiras, serras e ferramentas Makita com menores preços.",
    icon: "🔧",
    queries: [
      "furadeira-makita", "parafusadeira-makita", "serra-makita",
      "lixadeira-makita", "martelo-makita", "esmerilhadora-makita",
      "makita-18v", "makita-bateria", "kit-makita",
    ],
    related: ["bosch", "black-decker", "stanley"],
  },
  {
    slug: "bosch",
    name: "Bosch",
    description: "Furadeiras, parafusadeiras, serras e ferramentas Bosch em oferta.",
    icon: "🔧",
    queries: [
      "furadeira-bosch", "parafusadeira-bosch", "serra-bosch",
      "lixadeira-bosch", "martelo-bosch", "esmerilhadora-bosch",
      "bosch-12v", "bosch-18v", "bosch-bateria",
    ],
    related: ["makita", "black-decker", "deWalt"],
  },
  {
    slug: "black-decker",
    name: "Black+Decker",
    description: "Furadeiras, parafusadeiras, aspiradores e ferramentas Black+Decker com menores preços.",
    icon: "🔧",
    queries: [
      "furadeira-black-decker", "parafusadeira-black-decker",
      "aspirador-black-decker", "lixadeira-black-decker",
      "martelo-black-decker", "black-decker-20v",
      "kit-black-decker", "black-decker-bateria",
    ],
    related: ["makita", "bosch", "stanley"],
  },
  {
    slug: "cadence",
    name: "Cadence",
    description: "Airfryer, chapinha, secador, prancha e beleza Cadence com menores preços.",
    icon: "💇",
    queries: [
      "airfryer-cadence", "prancha-cadence", "secador-cadence",
      "chapinha-cadence", "escova-rotativa-cadence",
      "cafeteira-cadence", "sanduicheira-cadence",
      "ferro-cadence", "cadence-beleza",
    ],
    related: ["mondial", "philips", "remington"],
  },
  {
    slug: "stanley",
    name: "Stanley",
    description: "Furadeiras, ferramentas manuais, caixas e garrafas Stanley com menores preços.",
    icon: "🧰",
    queries: [
      "furadeira-stanley", "parafusadeira-stanley",
      "caixa-ferramentas-stanley", "jogo-brocas-stanley",
      "garrafa-stanley", "termo-stanley", "martelo-stanley",
      "chave-stanley", "kit-stanley",
    ],
    related: ["makita", "bosch", "black-decker"],
  },
  {
    slug: "microsoft-surface",
    name: "Microsoft Surface",
    description: "Surface Pro, Surface Laptop, Surface Go e acessórios Microsoft com menores preços.",
    icon: "💻",
    queries: [
      "surface-pro-9", "surface-pro-10", "surface-laptop-5",
      "surface-laptop-go", "surface-go-3", "surface-studio",
      "surface-pen", "surface-keyboard", "surface-dock",
      "surface-arc-mouse", "surface-headphones",
    ],
    related: ["dell", "lenovo", "apple"],
  },
  {
    slug: "canon",
    name: "Canon",
    description: "Câmeras Canon, lentes, impressoras e scanners com menores preços.",
    icon: "📷",
    queries: [
      "camera-canon-eos", "camera-canon-rebel", "camera-canon-r10",
      "lente-canon", "impressora-canon", "canon-pixma",
      "camera-canon-r50", "canon-r6", "canon-r8",
    ],
    related: ["sony", "nikon", "goPro"],
  },
  {
    slug: "nikon",
    name: "Nikon",
    description: "Câmeras Nikon, lentes e acessórios fotográficos com menores preços.",
    icon: "📷",
    queries: [
      "camera-nikon-d3500", "camera-nikon-z6", "camera-nikon-z50",
      "lente-nikon", "nikon-zfc", "nikon-z5",
      "camera-nikon-d7500", "nikon-coolpix",
    ],
    related: ["canon", "sony", "goPro"],
  },
]

export function getBrand(slug: string): BrandConfig | undefined {
  return BRANDS.find(b => b.slug === slug)
}

export function getAllBrandSlugs(): string[] {
  return BRANDS.map(b => b.slug)
}
